#!/usr/bin/env bash

# constants
DEST="org.mpris.MediaPlayer2.spotify"
PATH="/org/mpris/MediaPlayer2"
MEMB="org.mpris.MediaPlayer2.Player"

shopt -s expand_aliases

# get current song's metadata
function getMetadata {
  # prints the currently playing track in a parseable format.

  dbus-send \
  --print-reply \
  --dest=$DEST \
  $PATH \
  org.freedesktop.DBus.Properties.Get \
  string:"$MEMB" string:'Metadata' \
  | grep -Ev "^method" \
  | grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)' \
  | sed -E '2~2 a|' \
  | tr -d '\n' \
  | sed -E 's/\|/\n/g' \
  | sed -E 's/(xesam:)|(mpris:)//' \
  | sed -E 's/^"//' \
  | sed -E 's/"$//' \
  | sed -E 's/"+/|/' \
  | sed -E 's/ +/ /g'
}

# save metadata to variable so we don't have to call it multiple times
metadata=`getMetadata`

# get album cover url
cover="$(echo "$metadata" | grep "artUrl")"

# get artist
artist="$(echo "$metadata" | grep "artist")"

# get song title
song="$(echo "$metadata" | grep "title")"

# get album title
album="$(echo "$metadata" | grep "album|")"

# output everything
echo -e "$cover\n$song\n$artist\n$album"
